### PR TITLE
removing line break on message

### PR DESCRIPTION
**Pull request by felipeuematsu**
As mentioned here https://github.com/discord/endanger/issues/16, I'm removing the trailing newline by adding a replace on a newline just before the end of the line.

### CODE REVIEW

**Comment by felipeuematsu** [comment]
@jamiebuilds if you could take a look at this for me, please

**Comment by jamiebuilds** [comment]
Calling `.trim()` might be better

**Comment by felipeuematsu** [comment]
Doesn't trim only removes whitespaces and from both from end and start? We should only remove the artificially added `\n` at the end of the message

**Comment by jamiebuilds** [comment]
I disagree, we already call `.trim()` above, I don't want to have to adjust this regex again if the output changes.

**Comment by felipeuematsu** [comment]
Changed to `trim()`

**Comment by felipeuematsu** [comment]
@jamiebuilds Can you take a look now?

**Comment by jamiebuilds** [comment]
@athenayao could you merge this for me

**Comment by athenayao** [comment]
Done

**Pull request merged**
